# Generated by Django 5.0.6 on 2024-06-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('payment_due', models.DateField()),
                ('description', models.CharField(max_length=128)),
                ('payment_terms', models.IntegerField()),
                ('client_name', models.CharField(max_length=256)),
                ('client_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('DRAFT', 'Draft')], max_length=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.address')),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
    ]
