# Generated by Django 5.0.6 on 2024-06-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_invoice_items_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sender_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
