# Generated by Django 5.0.6 on 2024-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='ZD9201', max_length=6, primary_key=True, serialize=False),
        ),
    ]
