# Generated by Django 5.0.6 on 2024-06-22 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_address_id_alter_invoice_id_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f06b1d98-b1d7-406a-8c65-935c35c5ca95'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='FFLWAA', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c2c2137-a190-4533-a1fb-bfefb8a072e3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
