# Generated by Django 5.0.6 on 2024-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_address_id_alter_invoice_id_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='UGEWMG', max_length=6, primary_key=True, serialize=False),
        ),
    ]
