# Generated by Django 5.0.6 on 2024-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default='YHV9PW', max_length=6, primary_key=True, serialize=False),
        ),
    ]
